### ISSUE TITLE
About output .svg file size

### ISSUE THREAD

**Issue by uuugaga** [SwordHolderSH/Mang2Vec#2]
I ran this command:
```
python main.py --img=./image/Naruto.png --actor=./model/actor.pkl  --max_step=40 --divide=32
```
The size of Naruto.png is 81KB, but I obtained a 9.6MB SVG file named './output/1023.svg'. It did not become smaller.
When I used (p=16, k=20), the output size was 1.5MB. However, it also did not become smaller."

**Comment by SwordHolderSH** [comment]
Thanks for your question.

1)  You may need to change "use_PM = False" to "use_PM = Truth" , in the `main.py`.

2)  Vectorized results may not be smaller than images. In general, the higher the resolution of the input image, the more file sizes are reduced in vectorized results.

3) If the image has fewer color changes, the vectorized result will be smaller. If the color changes are more, it may be larger.

4) Our method more focus on vectorization accuracy, and is not good at reducing file sizes.
